### ISSUE TITLE
Remove and BigPicture

### ISSUE THREAD

**Issue by Jmi95110** [Hafas/node-steam-shortcuts#1]
Hi,

In first, good work.
Do you have some time for adding "bigpicture banner" support and adding  "shorcut removal"  function?

Thanks by advance,

**Comment by Hafas** [comment]
The purpose of this library is to edit the shortcuts.vdf-file, and since the bigpicture banners are not stored there, it won't be added into this library.
A `Shortcut`-Object has a `getAppID`-function though (oops - undocumented). To use a picture as a banner, you have to rename it to this appID and put it to `C:\Program Files (x86)\Steam\userdata\<your-user-id>\config\grid`.

A `removeShortcut`-function is doable though.

**Comment by Jmi95110** [comment]
Thanks for explaination.

Have a good day.
Regards.

**Comment by Jmi95110** [comment]
Thanks for explaination.

Have a good day.
Regards.
